#!/usr/bin/env python3
"""Post-process built HTML: swap image src to preview, store original in data-fullsrc.

After zensical build, every <img> in .md-content has src pointing to the
full-resolution image.  This script replaces those src values with the
corresponding .preview.jpg (which was generated by generate_image_previews.py)
and stashes the original path in data-fullsrc so the frontend JS can upgrade
to the full image after the preview has rendered.

While swapping, the real image width/height are read and written as
width/height attributes on the <img>.  That way the browser reserves the box
before any image bytes arrive, so the page doesn't shift around as images load
(no layout jank / CLS).

The glightbox <a href> is left untouched so lightbox still uses the full image.
"""

from __future__ import annotations

import re
import struct
import sys
import urllib.parse
from pathlib import Path

SITE = Path(__file__).resolve().parents[1] / "site"

# Match an entire <img ...> tag.
IMG_TAG_RE = re.compile(r"<img\b[^>]*>", re.IGNORECASE)
SRC_RE = re.compile(r'\bsrc="([^"]*)"', re.IGNORECASE)
PREVIEW_RE = re.compile(r"\.(png|jpe?g)(?=[\"?#]|$)", re.IGNORECASE)


def preview_path(original: str) -> str:
    """Return the preview filename for an image, or empty if not a PNG/JPEG."""
    if ".preview." in original:
        return ""
    if not PREVIEW_RE.search(original):
        return ""
    return PREVIEW_RE.sub(".preview.jpg", original)


def preview_exists(html_dir: Path, img_src: str, preview: str) -> bool:
    """Check if the preview file actually exists on disk."""
    # HTML paths may be URL-encoded; decode for filesystem lookup.
    src_path = urllib.parse.unquote(img_src)
    pv_path = urllib.parse.unquote(preview)
    candidate = (html_dir / pv_path).resolve()
    return candidate.is_file()


def read_image_size(path: Path):
    """Return (width, height) for a PNG/JPEG, or None if unreadable."""
    try:
        data = path.read_bytes()
    except OSError:
        return None

    head = data[:24]
    # PNG: signature + IHDR (width/height at fixed offsets)
    if head[:8] == b"\x89PNG\r\n\x1a\n" and head[12:16] == b"IHDR":
        w, h = struct.unpack(">II", head[16:24])
        if 0 < w < 100000 and 0 < h < 100000:
            return w, h

    # JPEG: walk segments until SOF (start of frame)
    if data[:2] == b"\xff\xd8":
        i = 2
        n = len(data)
        sof = {0xC0, 0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7,
               0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF}
        while i + 4 <= n:
            if data[i] != 0xFF:
                return None
            while i < n and data[i] == 0xFF:
                i += 1
            if i >= n:
                return None
            marker = data[i]
            i += 1
            if marker in (0xD8, 0x01) or 0xD0 <= marker <= 0xD7:
                continue
            if marker in sof:
                if i + 7 <= n:
                    # i points at segment length; layout is:
                    #   length(2) precision(1) height(2) width(2)
                    h = int.from_bytes(data[i + 3 : i + 5], "big")
                    w = int.from_bytes(data[i + 5 : i + 7], "big")
                    if 0 < w < 100000 and 0 < h < 100000:
                        return w, h
                return None
            if i + 2 > n:
                return None
            i += int.from_bytes(data[i : i + 2], "big")

    return None


def _add_lqip_class(tag: str) -> str:
    """Ensure the img tag carries the 'lqip' class for blur-up transition."""
    if re.search(r'\blqip\b', tag, re.IGNORECASE):
        return tag
    m_cls = re.search(r'\bclass="([^"]*)"', tag, re.IGNORECASE)
    if m_cls:
        existing = m_cls.group(1)
        return tag.replace(f'class="{existing}"', f'class="{existing} lqip"', 1)
    return re.sub(r'^(<img\b)', r'\1 class="lqip"', tag, count=1, flags=re.IGNORECASE)


def add_dimensions(tag: str, html_dir: Path, original: str) -> str:
    """Insert width/height (from the full image) if not already present.

    Reads the size of the full-resolution image (data-fullsrc, else current
    src) so the injected attributes carry the real proportions.  Browsers use
    them as an aspect-ratio placeholder before load; after load Material's
    default `max-width: 100%` reflows big images back to container width, so
    they are never locked to a small preview size.
    """
    # Drop any previously script-injected numeric width/height so re-runs are
    # idempotent (explicit Markdown sizes are non-numeric or carry units, so
    # they are left untouched).
    tag = re.sub(r'\s+width="[0-9]+"', "", tag, flags=re.IGNORECASE)
    tag = re.sub(r'\s+height="[0-9]+"', "", tag, flags=re.IGNORECASE)

    # Prefer the full image the JS will upgrade to.
    src = original
    m_full = re.search(r'\bdata-fullsrc="([^"]*)"', tag, re.IGNORECASE)
    if m_full:
        src = m_full.group(1)
    size = read_image_size(html_dir / urllib.parse.unquote(src))
    if not size:
        return tag
    w, h = size
    return re.sub(r"^(<img\b)", rf'\1 width="{w}" height="{h}"', tag, count=1, flags=re.IGNORECASE)


def process_tag(tag: str, html_dir: Path) -> str:
    """Swap src -> preview and add size placeholder to a single <img> tag."""
    m_src = SRC_RE.search(tag)
    if not m_src:
        return tag
    original = m_src.group(1)

    # Swap to preview when available and not already done.
    if ".preview." not in original.lower():
        pv = preview_path(original)
        if (
            pv
            and preview_exists(html_dir, original, pv)
            and not re.search(r"\bdata-fullsrc=", tag, re.IGNORECASE)
        ):
            tag = re.sub(
                SRC_RE,
                f'src="{pv}" data-fullsrc="{original}"',
                tag,
                count=1,
            )
            # Add lqip class for CSS blur-up transition
            tag = _add_lqip_class(tag)

    # If the image already has data-fullsrc (previously swapped) but no lqip class,
    # add it now so existing builds also get the blur-up transition.
    if re.search(r"\bdata-fullsrc=", tag, re.IGNORECASE):
        tag = _add_lqip_class(tag)

    # Reserve the box so the page doesn't shift on image load.
    return add_dimensions(tag, html_dir, original)


def process_file(html_path: Path) -> bool:
    changed = False
    html = html_path.read_text(encoding="utf-8")
    html_dir = html_path.parent

    def replace_tag(m: re.Match) -> str:
        nonlocal changed
        new_tag = process_tag(m.group(0), html_dir)
        if new_tag != m.group(0):
            changed = True
        return new_tag

    new_html = IMG_TAG_RE.sub(replace_tag, html)

    if changed:
        html_path.write_text(new_html, encoding="utf-8")
        print(f"  patched: {html_path.relative_to(SITE)}")
    return changed


def main() -> None:
    count = 0
    for html_file in sorted(SITE.rglob("*.html")):
        if process_file(html_file):
            count += 1
    print(f"Done: {count} file(s) patched.")


if __name__ == "__main__":
    main()
