#!/usr/bin/env python3
"""Post-process built HTML: swap image src to preview, store original in data-fullsrc.

After zensical build, every <img> in .md-content has src pointing to the
full-resolution image.  This script replaces those src values with the
corresponding .preview.jpg (which was generated by generate_image_previews.py)
and stashes the original path in data-fullsrc so the frontend JS can upgrade
to the full image after the preview has rendered.

The glightbox <a href> is left untouched so lightbox still uses the full image.
"""

from __future__ import annotations

import re
import sys
import urllib.parse
from pathlib import Path

SITE = Path(__file__).resolve().parents[1] / "site"

# Match <img ... src="path/to/foo.ext" ... />
IMG_RE = re.compile(r'<img\b[^>]*\bsrc="([^"]*)"', re.IGNORECASE)
SRC_RE = re.compile(r'\bsrc="([^"]*)"', re.IGNORECASE)
PREVIEW_RE = re.compile(r'\.(png|jpe?g)(?=["?#]|$)', re.IGNORECASE)


def preview_path(original: str) -> str:
    """Return the preview filename for an image, or empty if not an image."""
    if ".preview." in original:
        return ""
    return PREVIEW_RE.sub(".preview.jpg", original)


def preview_exists(html_dir: Path, img_src: str, preview: str) -> bool:
    """Check if the preview file actually exists on disk."""
    # HTML paths may be URL-encoded; decode for filesystem lookup.
    src_path = urllib.parse.unquote(img_src)
    pv_path = urllib.parse.unquote(preview)
    candidate = (html_dir / pv_path).resolve()
    return candidate.is_file()


def process_file(html_path: Path) -> bool:
    changed = False
    html = html_path.read_text(encoding="utf-8")
    html_dir = html_path.parent

    def replace_src(m: re.Match) -> str:
        nonlocal changed
        full_tag = m.group(0)  # entire <img ...> tag
        original = m.group(1)  # the src value

        pv = preview_path(original)
        if not pv:
            return full_tag

        if not preview_exists(html_dir, original, pv):
            return full_tag

        # Already has data-fullsrc? Skip.
        if re.search(r'\bdata-fullsrc=', full_tag, re.IGNORECASE):
            return full_tag

        # Don't touch if src is already a preview
        if ".preview." in original.lower():
            return full_tag

        changed = True
        # Replace src and add data-fullsrc
        result = re.sub(
            SRC_RE,
            f'src="{pv}" data-fullsrc="{original}"',
            full_tag,
            count=1,
        )
        return result

    new_html = IMG_RE.sub(replace_src, html)

    if changed:
        html_path.write_text(new_html, encoding="utf-8")
        print(f"  patched: {html_path.relative_to(SITE)}")
    return changed


def main() -> None:
    count = 0
    for html_file in sorted(SITE.rglob("*.html")):
        if process_file(html_file):
            count += 1
    print(f"Done: {count} file(s) patched.")


if __name__ == "__main__":
    main()
